### ISSUE TITLE
Add compile?

### ISSUE THREAD

**Issue by BioAleks** [FreeDenny9700/S4_LUA_Decompiler#1]
Maybe you add compile program too?
I use online internet compile :3.

This tool need update or decompile no need update (after blub after here lib)?

**Comment by FreeDenny9700** [comment]
This tool no need update for now, it work

**Comment by BioAleks** [comment]
So, what about compile program?

**Comment by BioAleks** [comment]
No answer?

**Comment by FreeDenny9700** [comment]
This program can't compile LUA files. Try to import LUA file without compiling

**Comment by BioAleks** [comment]
You no read? 

> Maybe you add compile program too?

> Second is... add decompiled files in client. Yes, they work, but when i just add new code (with breaker) and add this decompiled files in the client - some weapons sounds be missed (client no play this sound files). It's no new code problem.

**Comment by FreeDenny9700** [comment]
It's a your problem...
For me it work perfectly

**Comment by BioAleks** [comment]
pf. I no test your tool. Test by yourself. It's your problem.

**Comment by FreeDenny9700** [comment]
I have no problem bro, Happy Life :)
