### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by BioAleks** [FreeDenny9700/S4_LUA_Decompiler#2]
Your tool rename word "in" to "out" in files when decompile.
And file rename too.

I try to decompile new .lua (from korea - attack indexer) and it's no decompile.
Same problem with breaker lua file.
So, they have another lua version?
Korea client - 2016.
Try client 2014 - working.

Second is... add decompiled files in client.
Yes, they work, but when i just add new code (with breaker) and add decompiled files in the client - some weapons sounds be missed (client no play this sound files).
What problem here? Need to compile?

**Comment by FreeDenny9700** [comment]
Yes, korea client have an other version of lua file

**Comment by BioAleks** [comment]
Example: your have file name "blablainblabla"
tool rename it to "blalblaoutblabla".

So, maybe sounds missed by this problem.
But i no see in file that index be rename to outndex or something this...

**Comment by FreeDenny9700** [comment]
Today check my code for fix this problem.
